<a href="https://colab.research.google.com/github/nibchee/data_science_machine_learning/blob/main/Regression_Metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv("/content/50_Startups.csv")

In [ ]:
df.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:

X = df.iloc[:,0].values
y = df.iloc[:,-1].values

In [ ]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
len(X_train)

40

In [ ]:
len(X_test)

10

In [ ]:
X_test

array([ 66051.52, 100671.96, 101913.08,  27892.92, 153441.51,  72107.6 ,
        20229.59,  61136.38,  73994.56, 142107.34])

In [ ]:
X_test

array([ 66051.52, 100671.96, 101913.08,  27892.92, 153441.51,  72107.6 ,
        20229.59,  61136.38,  73994.56, 142107.34])

In [ ]:
X_train

array([ 55493.95,  46014.02,  75328.87,  46426.07,  91749.16, 130298.13,
       119943.24,   1000.23,    542.05,  65605.48, 114523.61,  61994.48,
        63408.86,  78013.11,  23640.93,  76253.86,  15505.73, 120542.52,
        91992.39,  64664.71, 131876.9 ,  94657.16,  28754.33,      0.  ,
       162597.7 ,  93863.75,  44069.95,  77044.01, 134615.46,  67532.53,
        28663.76,  78389.47,  86419.7 , 123334.88,  38558.51,   1315.46,
       144372.41, 165349.2 ,      0.  ,  22177.74])

In [ ]:
# The reshape operations are not needed after correct data extraction and encoding.
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)